# Keras Network to Classify Odd/Even Numbers

In [1]:
import warnings
warnings.filterwarnings('ignore')

# imports
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from keras.models import Model

Using TensorFlow backend.


## Big Picture
- Supervised learning
- Neural nets try to approximate any arbitrary function, given enough data

## Goal
- Train a neural network classifier to classify if an integer is odd or even.

## Workflow
1. Setup training data
2. Create binary encoding for the input layer
3. Create binary decoding for the ouput layer
4. Create the model, add layers, and train/fit
5. Create predictions on new data
3. Evaluate the performance of the classifier

In [2]:
# Specify the number of binary digits. 
NUM_DIGITS = 10

In [3]:
## Setup the training data for 101-1024. 1024 is the highest number countable with 10 binary digits
raw_training_data = np.array(range(101, 2**NUM_DIGITS))

In [4]:
## Binary Encoding function
# In order to binary encode the input values
def binary_encode(i, NUM_DIGITS):
    return np.array([i >> d & 1 for d in range(NUM_DIGITS)])

In [5]:
print(1, binary_encode(1, NUM_DIGITS))
print(2, binary_encode(2, NUM_DIGITS))
print(3, binary_encode(3, NUM_DIGITS))
print(4, binary_encode(4, NUM_DIGITS))

1 [1 0 0 0 0 0 0 0 0 0]
2 [0 1 0 0 0 0 0 0 0 0]
3 [1 1 0 0 0 0 0 0 0 0]
4 [0 0 1 0 0 0 0 0 0 0]


In [6]:
# encode the training data
encoded_training_data = [binary_encode(i, NUM_DIGITS) for i in raw_training_data]

In [7]:
x_train = np.array(encoded_training_data)

In [8]:
x_trainencode_even_odd

array([[1, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [9]:
# Encode "even" and "odd" to zero or 1
# If we had more than 2 options, we'd one hot encode and make an array
def encode_even_odd(i):
    if i % 2 == 0:
        return [0]
    else:
        return [1]

assert encode_even_odd(2) == [0]
assert encode_even_odd(3) == [1]

In [10]:
# y_train is the encoded output. 
# This is our "labeled data" for supervised learning
y_train = np.array([encode_even_odd(i) for i in range(101, 2 ** NUM_DIGITS)])

## Compare raw inputs to the lables
- The first five values in the input tensor are 101, 102, 103, 104, and 105
- The encoded labels specify "odd", "even", "odd", "even", and then "odd"
- Remember that training a classifier is supervised learning with labeled data

In [11]:
print("Raw training data", raw_training_data[:5])
print(y_train[:5])

Raw training data [101 102 103 104 105]
[[1]
 [0]
 [1]
 [0]
 [1]]


In [12]:
# Convert from binary back to the ouput string
def decode_even_odd(n):
    if n == 0:
        return "even"
    else:
        return "odd"

assert decode_even_odd(0) == 'even'
assert decode_even_odd(1) == 'odd'

In [13]:
# Another way I've seen this decoding written (especially with one hot encoded options)
# Convert from binary back to the ouput string
def decode_even_odd2(n):
    return ["even", "odd"][n]

assert decode_even_odd2(0) == 'even'
assert decode_even_odd2(1) == 'odd'

In [22]:
# Now let's build our model, add layers, compile, and fit it!
model = Sequential()

## Add the model's layers.
# These are defaults and they work pretty well
model.add(Dense(1000, input_dim=NUM_DIGITS, activation="relu"))
model.add(Dense(1000, activation="relu"))
model.add(Dense(4, activation="softmax"))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adagrad', metrics=["accuracy"])

In [23]:
# Fit the model on the training data
model.fit(x_train, y_train, nb_epoch=100, batch_size=128)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/100
923/923 [==============================] - 1s 1ms/step - loss: 1.8010 - acc: 0.7801
Epoch 2/100
923/923 [==============================] - 0s 174us/step - loss: 0.0045 - acc: 1.0000
Epoch 3/100
923/923 [==============================] - 0s 164us/step - loss: 0.0018 - acc: 1.0000
Epoch 4/100
923/923 [==============================] - 0s 160us/step - loss: 8.9433e-04 - acc: 1.0000
Epoch 5/100
923/923 [==============================] - 0s 158us/step - loss: 4.9319e-04 - acc: 1.0000
Epoch 6/100
923/923 [==============================] - 0s 163us/step - loss: 2.9449e-04 - acc: 1.0000
Epoch 7/100
923/923 [==============================] - 0s 164us/step - loss: 1.9297e-04 - acc: 1.0000
Epoch 8/100
923/923 [==============================] - 0s 167us/step - loss: 1.3542e-04 - acc: 1.0000
Epoch 9/100
923/923 [==============================] - 0s 157us/step - loss: 9.6860e-05 - acc: 1.0000
E

923/923 [==============================] - 0s 162us/step - loss: 2.5264e-06 - acc: 1.0000
Epoch 76/100
923/923 [==============================] - 0s 159us/step - loss: 2.4881e-06 - acc: 1.0000
Epoch 77/100
923/923 [==============================] - 0s 163us/step - loss: 2.4480e-06 - acc: 1.0000
Epoch 78/100
923/923 [==============================] - 0s 163us/step - loss: 2.4067e-06 - acc: 1.0000
Epoch 79/100
923/923 [==============================] - 0s 158us/step - loss: 2.3680e-06 - acc: 1.0000
Epoch 80/100
923/923 [==============================] - 0s 162us/step - loss: 2.3359e-06 - acc: 1.0000
Epoch 81/100
923/923 [==============================] - 0s 160us/step - loss: 2.2926e-06 - acc: 1.0000
Epoch 82/100
923/923 [==============================] - 0s 162us/step - loss: 2.2621e-06 - acc: 1.0000
Epoch 83/100
923/923 [==============================] - 0s 161us/step - loss: 2.2294e-06 - acc: 1.0000
Epoch 84/100
923/923 [==============================] - 0s 161us/step - loss: 2.1996e-

In [26]:
# Setup x_test  fizzbuzz for prime numbers from 1 to 100
numbers = np.arange(1, 101)
x_test = np.transpose(binary_encode(numbers, NUM_DIGITS))
y_test = model.predict_classes(x_test)

In [28]:
# Setup predicted output
predictions = np.vectorize(decode_even_odd)(y_test)
print (predictions)

['odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd'
 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even'
 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd'
 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even'
 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd'
 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even'
 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd'
 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even'
 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd'
 'even']


In [30]:
actual = np.array([])
for i in numbers:
    if i % 2 == 0:
        actual = np.append(actual, "even")
    else:
        actual = np.append(actual, "odd")

actual

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even'], dtype='<U32')

In [34]:
# Let's evaluate the model's predictions
evaluate = np.array(actual == predictions)
print (np.count_nonzero(evaluate == True) / 100)

1.0


### Ok, 100% accuracy... but what if we send the model random numbers?

In [59]:
random_numbers = np.random.randint(1023, size=10000)
random_numbers[:10]

array([721, 715, 682, 765, 671, 609, 321, 254, 960, 677])

In [60]:
x_test = np.transpose(binary_encode(random_numbers, NUM_DIGITS))
y_test = model.predict_classes(x_test)

In [61]:
predictions = np.vectorize(decode_even_odd)(y_test)

In [62]:
predictions.shape

(10000,)

In [63]:
actual = np.array([])
for i in random_numbers:
    if i % 2 == 0:
        actual = np.append(actual, "even")
    else:
        actual = np.append(actual, "odd")

actual

array(['odd', 'odd', 'even', ..., 'odd', 'odd', 'even'], dtype='<U32')

In [64]:
actual.shape

(10000,)

In [65]:
# Let's evaluate the model's predictions
evaluate = np.array(actual == predictions)
print (np.count_nonzero(evaluate == True) / 100)

100.0
